/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



/**
 *
 * @author daw1
 */
public class DialogoOperar extends javax.swing.JDialog {

    /**
     * Creates new form DialogoOperar
     */
    public DialogoOperar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Operaciones = new javax.swing.ButtonGroup();
        Ingresar = new javax.swing.JRadioButton();
        Reintegrar = new javax.swing.JRadioButton();
        Consultar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tCantidad = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operar con cuenta");

        Operaciones.add(Ingresar);
        Ingresar.setText("Ingresar");
        Ingresar.setActionCommand("ingresar");

        Operaciones.add(Reintegrar);
        Reintegrar.setText("Reintegrar");
        Reintegrar.setActionCommand("reintegrar");

        Operaciones.add(Consultar);
        Consultar.setSelected(true);
        Consultar.setText("Consultar");
        Consultar.setActionCommand("consultar");

        jLabel1.setText("Cantidad");

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(Reintegrar)
                        .addGap(31, 31, 31)
                        .addComponent(Consultar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingresar)
                    .addComponent(Reintegrar)
                    .addComponent(Consultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        opcion = ACEPTAR;
        setVisible(false);
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        opcion = CANCELAR;
        setVisible(true);
    }//GEN-LAST:event_CancelarActionPerformed

    public String getOperacion() {
        return Operaciones.getSelection().getActionCommand();
    }

    public int mostrarDialogo() {
        opcion = CANCELAR;
        setVisible(true);
        return opcion;
    }
    
    public float getCantidad(){
        return Float.parseFloat(tCantidad.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JRadioButton Consultar;
    private javax.swing.JRadioButton Ingresar;
    private javax.swing.ButtonGroup Operaciones;
    private javax.swing.JRadioButton Reintegrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tCantidad;
    // End of variables declaration//GEN-END:variables
    
    public static final int ACEPTAR = 1;
    public static final int CANCELAR = 0;
    private int opcion;

}
