/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.IControladorBanco;
import Vista.DialogoCrear;
import Modelo.Banco;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author daw1
 */
public class VistaBanco extends javax.swing.JFrame implements IVistaBanco {

    /**
     * Creates new form VistaBanco
     */
    public VistaBanco() {
        initComponents();
        initComponents2();
    }

    public void setControlador(IControladorBanco controlador) {
        this.controlador = controlador;
    }

    private void initComponents2() {
        dialogoCrear = new DialogoCrear(this, true);
        dialogoOperar = new DialogoOperar(this, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //De esta vetana hay que borrar lo que trae la tabla por defecto
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSeparator2 = new javax.swing.JSeparator();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        Titular = new javax.swing.JLabel();
        Saldo = new javax.swing.JLabel();
        MosCodigo = new javax.swing.JTextField();
        MosTitular = new javax.swing.JTextField();
        MosSaldo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCuentas = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        MostrarCuentas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MSalir = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        NuevaCuenta = new javax.swing.JMenuItem();
        CancelarCuenta = new javax.swing.JMenuItem();
        Operar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista Banco");

        Codigo.setText("Codigo");

        Titular.setText("Titular");

        Saldo.setText("Saldo");

        MosCodigo.setEditable(false);
        MosCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosCodigoActionPerformed(evt);
            }
        });

        MosTitular.setEditable(false);

        MosSaldo.setEditable(false);

        TablaCuentas.setAutoCreateRowSorter(true);
        TablaCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCuentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaCuentas);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        MostrarCuentas.setText("Mostrar cuentas");
        MostrarCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(MostrarCuentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(Saldo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Codigo)
                            .addComponent(Titular))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MosSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MosTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo)
                    .addComponent(MosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titular)
                    .addComponent(MosTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Saldo)
                    .addComponent(MosSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(MostrarCuentas))
                .addContainerGap())
        );

        Archivo.setText("Archivo");
        Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoActionPerformed(evt);
            }
        });

        Nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);
        Archivo.add(jSeparator1);

        MSalir.setText("Salir");
        MSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSalirActionPerformed(evt);
            }
        });
        Archivo.add(MSalir);

        jMenuBar1.add(Archivo);

        Editar.setText("Banco");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        NuevaCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        NuevaCuenta.setText("Nueva cuenta");
        NuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaCuentaActionPerformed(evt);
            }
        });
        Editar.add(NuevaCuenta);

        CancelarCuenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        CancelarCuenta.setText("Cancelar cuenta");
        CancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarCuentaActionPerformed(evt);
            }
        });
        Editar.add(CancelarCuenta);

        Operar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Operar.setText("Operar con cuentas");
        Operar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperarActionPerformed(evt);
            }
        });
        Editar.add(Operar);

        jMenuBar1.add(Editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarActionPerformed

    private void NuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaCuentaActionPerformed
        // TODO add your handling code here:
        if (dialogoCrear.mostrarDialogo() == dialogoCrear.ACEPTAR) {
            controlador.abrir();
        }
    }//GEN-LAST:event_NuevaCuentaActionPerformed

    private void CancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarCuentaActionPerformed
        // TODO add your handling code here:
        controlador.cancelar();
    }//GEN-LAST:event_CancelarCuentaActionPerformed

    private void OperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperarActionPerformed
        // TODO add your handling code here:
        controlador.operar();
    }//GEN-LAST:event_OperarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.guardar();
        }

    }//GEN-LAST:event_GuardarActionPerformed

    private void ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ArchivoActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        // TODO add your handling code here:
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.cargar();
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void MostrarCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarCuentasActionPerformed
        // TODO add your handling code here:
        controlador.listar();
    }//GEN-LAST:event_MostrarCuentasActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void MSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_MSalirActionPerformed

    private void MosCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MosCodigoActionPerformed

    private void TablaCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCuentasMouseClicked
        // TODO add your handling code here:
        int fila = TablaCuentas.getSelectedRow();
        MosCodigo.setText((String)TablaCuentas.getValueAt(fila, 0));
        MosTitular.setText((String)TablaCuentas.getValueAt(fila, 1));
        MosSaldo.setText(Float.toString((float)TablaCuentas.getValueAt(fila, 2)));
    }//GEN-LAST:event_TablaCuentasMouseClicked


    @Override
    public String getCodigo() {
        return dialogoCrear.getCodigo();
    }

    @Override
    public String getTitular() {
        return dialogoCrear.getTitular();
    }

    @Override
    public float getSaldo() {
        return dialogoCrear.getSaldo();
    }

    @Override
    public String getCodigoCuenta() {
        //return dialogoCrear.getCodigo();
        return JOptionPane.showInputDialog(this, "Introduce codigo de la cuenta");
    }

    @Override
    public int getOperacion() {
        int operacion = 0;
        if (dialogoOperar.mostrarDialogo() == 1) {
            switch (dialogoOperar.getOperacion()) {
                case "ingresar":
                    operacion = 1;
                    break;
                case "reintegrar":
                    operacion = 2;
                    break;
                case "consultar":
                    operacion = 3;
                    break;
            }
        }
        return operacion;
    }

    @Override
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    @Override
    public void mostrar() {
        setVisible(true);
    }

    private DialogoCrear dialogoCrear;
    private DialogoOperar dialogoOperar;
    private IControladorBanco controlador;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem CancelarCuenta;
    private javax.swing.JLabel Codigo;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JMenuItem MSalir;
    private javax.swing.JTextField MosCodigo;
    private javax.swing.JTextField MosSaldo;
    private javax.swing.JTextField MosTitular;
    private javax.swing.JButton MostrarCuentas;
    private javax.swing.JMenuItem NuevaCuenta;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JMenuItem Operar;
    private javax.swing.JLabel Saldo;
    private javax.swing.JButton Salir;
    private javax.swing.JTable TablaCuentas;
    private javax.swing.JLabel Titular;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    @Override
    public float getCantidad() {
        return dialogoOperar.getCantidad();
    }

    @Override
    public String getArchivoAbrir() {
        return jFileChooser1.getSelectedFile().getPath();
    }

    @Override
    public String getArchivoGuardar() {
        return jFileChooser1.getSelectedFile().getPath();
    }

    @Override
    public void mostrarCuentas(Object[][] listado) {
        TablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
                listado,
                new String[]{
                    "Codigo", "Titulo", "Saldo"
                }
        ));
    }

    @Override
    public void mostrarCodigo(String codigo) {
        MosCodigo.setText(codigo);
    }

    @Override
    public void mostrarTitular(String titular) {
        MosTitular.setText(titular);
    }

    @Override
    public void mostrarSaldo(float saldo) {
        MosSaldo.setText(Float.toString(saldo));
    }

    @Override
    public void setModel(AbstractTableModel modelo) {
        TablaCuentas.setModel(modelo); //Tabla autoactualizable (No se como explicarme)
    }

}
